# prettier.io config 
# uses cosmicconfig, supports YAML, JSON, JS, TOML
printWidth: 80
tabWidth: 2
singleQuote: true
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: false
parser: "babel"
semi: true
requirePragma: false
proseWrap: "preserve"
arrowParens: "avoid"
htmlWhitespaceSensitivity: "css"
quoteProps: "as-needed"